[package]
name = "dumper"
version = "0.1.0"
authors = ["Batbold Dashzeveg <dbatbold@gmail.com>"]
edition = "2018"
license = "MIT"
description = "HTTP text dumper"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
